#if !canImport(ObjectiveC)
import XCTest

extension CredentialsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CredentialsTests = [
        ("testCredentialsCreation", testCredentialsCreation),
    ]
}

extension DirectionsErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DirectionsErrorTests = [
        ("testEquality", testEquality),
        ("testFailureReasons", testFailureReasons),
        ("testRecoverySuggestions", testRecoverySuggestions),
    ]
}

extension GeoJSONTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GeoJSONTests = [
        ("testInitialization", testInitialization),
        ("testZeroLengthWorkaround", testZeroLengthWorkaround),
    ]
}

extension IntersectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntersectionTests = [
        ("testCoding", testCoding),
    ]
}

extension MatchOptionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MatchOptionsTests = [
        ("testCoding", testCoding),
        ("testRouteOptionsConvertedFromMatchOptions", testRouteOptionsConvertedFromMatchOptions),
        ("testWaypointSerialization", testWaypointSerialization),
    ]
}

extension MatchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MatchTests = [
        ("testCoding", testCoding),
    ]
}

extension QuickLookTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QuickLookTests = [
        ("testQuickLookURL", testQuickLookURL),
    ]
}

extension RoadTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RoadTests = [
        ("testDestinations", testDestinations),
        ("testEmpty", testEmpty),
        ("testExitCodes", testExitCodes),
        ("testNamesCodes", testNamesCodes),
        ("testRotaryNames", testRotaryNames),
    ]
}

extension RouteLegTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouteLegTests = [
        ("testSegmentRanges", testSegmentRanges),
    ]
}

extension RouteOptionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouteOptionsTests = [
        ("testApproachesURLQueryParams", testApproachesURLQueryParams),
        ("testCoding", testCoding),
        ("testDecimalPrecision", testDecimalPrecision),
        ("testMissingApproaches", testMissingApproaches),
        ("testResponseWithDestinationName", testResponseWithDestinationName),
        ("testResponseWithManuallySetDestinationName", testResponseWithManuallySetDestinationName),
        ("testResponseWithoutDestinationName", testResponseWithoutDestinationName),
        ("testWaypointSerialization", testWaypointSerialization),
    ]
}

extension RouteRefreshTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouteRefreshTests = [
        ("testDecoding", testDecoding),
        ("testEncoding", testEncoding),
    ]
}

extension RouteResponseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouteResponseTests = [
        ("testRouteResponseEncodingAndDecoding", testRouteResponseEncodingAndDecoding),
    ]
}

extension RouteStepTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouteStepTests = [
        ("testCoding", testCoding),
        ("testDecoding", testDecoding),
        ("testEncodingPronunciations", testEncodingPronunciations),
        ("testRouteStepTypicalTravelTime", testRouteStepTypicalTravelTime),
    ]
}

extension RouteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouteTests = [
        ("testCoding", testCoding),
        ("testNullVoiceLocaleRoundtrip", testNullVoiceLocaleRoundtrip),
        ("testRouteTypicalTravelTime", testRouteTypicalTravelTime),
    ]
}

extension SpokenInstructionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpokenInstructionTests = [
        ("testCoding", testCoding),
        ("testEquality", testEquality),
    ]
}

extension TransportTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TransportTypeTests = [
        ("testDecoding", testDecoding),
    ]
}

extension VisualInstructionComponentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VisualInstructionComponentTests = [
        ("testImageComponent", testImageComponent),
        ("testLaneComponent", testLaneComponent),
        ("testTextComponent", testTextComponent),
        ("testUnrecognizedComponent", testUnrecognizedComponent),
    ]
}

extension WalkingOptionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WalkingOptionsTests = [
        ("testURLQueryParams", testURLQueryParams),
    ]
}

extension WaypointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WaypointTests = [
        ("testAccuracies", testAccuracies),
        ("testCoding", testCoding),
        ("testEquality", testEquality),
        ("testHeading", testHeading),
        ("testSeparatesLegs", testSeparatesLegs),
        ("testTracepointEquality", testTracepointEquality),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CredentialsTests.__allTests__CredentialsTests),
        testCase(DirectionsErrorTests.__allTests__DirectionsErrorTests),
        testCase(GeoJSONTests.__allTests__GeoJSONTests),
        testCase(IntersectionTests.__allTests__IntersectionTests),
        testCase(MatchOptionsTests.__allTests__MatchOptionsTests),
        testCase(MatchTests.__allTests__MatchTests),
        testCase(QuickLookTests.__allTests__QuickLookTests),
        testCase(RoadTests.__allTests__RoadTests),
        testCase(RouteLegTests.__allTests__RouteLegTests),
        testCase(RouteOptionsTests.__allTests__RouteOptionsTests),
        testCase(RouteRefreshTests.__allTests__RouteRefreshTests),
        testCase(RouteResponseTests.__allTests__RouteResponseTests),
        testCase(RouteStepTests.__allTests__RouteStepTests),
        testCase(RouteTests.__allTests__RouteTests),
        testCase(SpokenInstructionTests.__allTests__SpokenInstructionTests),
        testCase(TransportTypeTests.__allTests__TransportTypeTests),
        testCase(VisualInstructionComponentTests.__allTests__VisualInstructionComponentTests),
        testCase(WalkingOptionsTests.__allTests__WalkingOptionsTests),
        testCase(WaypointTests.__allTests__WaypointTests),
    ]
}
#endif
