#if !canImport(ObjectiveC)
import XCTest

extension IntersectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntersectionTests = [
        ("testCoding", testCoding),
    ]
}

extension RoadTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RoadTests = [
        ("testDestinations", testDestinations),
        ("testEmpty", testEmpty),
        ("testExitCodes", testExitCodes),
        ("testNamesCodes", testNamesCodes),
        ("testRotaryNames", testRotaryNames),
    ]
}

extension RouteOptionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouteOptionsTests = [
        ("testApproachesURLQueryParams", testApproachesURLQueryParams),
        ("testCoding", testCoding),
        ("testCodingV4", testCodingV4),
        ("testCopying", testCopying),
        ("testDecimalPrecision", testDecimalPrecision),
        ("testMissingApproaches", testMissingApproaches),
        ("testResponseWithDestinationName", testResponseWithDestinationName),
        ("testResponseWithManuallySetDestinationName", testResponseWithManuallySetDestinationName),
        ("testResponseWithoutDestinationName", testResponseWithoutDestinationName),
        ("testWaypointSerialization", testWaypointSerialization),
    ]
}

extension RouteStepTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouteStepTests = [
        ("testCoding", testCoding),
    ]
}

extension VisualInstructionComponentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VisualInstructionComponentTests = [
        ("testJSONInitialization", testJSONInitialization),
    ]
}

extension WaypointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WaypointTests = [
        ("testCoding", testCoding),
        ("testCopying", testCopying),
        ("testSeparatesLegs", testSeparatesLegs),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(IntersectionTests.__allTests__IntersectionTests),
        testCase(RoadTests.__allTests__RoadTests),
        testCase(RouteOptionsTests.__allTests__RouteOptionsTests),
        testCase(RouteStepTests.__allTests__RouteStepTests),
        testCase(VisualInstructionComponentTests.__allTests__VisualInstructionComponentTests),
        testCase(WaypointTests.__allTests__WaypointTests),
    ]
}
#endif
