use_frameworks!

def shared_pods
  pod 'MapboxDirections.swift', :path => '..'
  pod 'Mapbox-iOS-SDK', '~> 3.3'
end

target 'Example (Swift)' do
  platform :ios, '8.0'
  shared_pods
end

target 'Example (Objective-C)' do
  platform :ios, '8.0'
  shared_pods
end
