codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

ignore:
  - "Directions Example"
  - "Tests"

coverage:
  status:
    project:
      default:
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
